import type { Challenge } from "@/lib/punishment/schema";

// 「一男一女」真心话正式题库 V1.0（Human 审核入库，118 题）。
// 来源：content/真心话（一男一女版本）/.../truth-bank.json（追溯真源，不进运行时）。
// 按导入说明：不映射盾牌标签（contentTags 全空）；本包无计时（timerSeconds 全为 null）；题面未改写。
export const truthPair: Challenge[] = [
    { id: "TR-L1-001", level: 1, zh: "你觉得自己最吸引人的一点是什么？", en: "What do you think is your most attractive quality?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-002", level: 1, zh: "你最喜欢别人夸你什么？", en: "What kind of compliment do you like hearing most?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-003", level: 1, zh: "你觉得自己脸皮厚还是薄？", en: "Would you say you're thick-skinned or thin-skinned?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-004", level: 1, zh: "你小时候最常被叫什么绰号？", en: "What nickname did people call you most when you were a kid?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-005", level: 1, zh: "什么事情最容易把你逗笑？", en: "What makes you laugh most easily?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-006", level: 1, zh: "你最喜欢哪种拥抱？", en: "What kind of hug do you like most?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-007", level: 1, zh: "你最喜欢别人怎么叫你？", en: "What do you like people to call you?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-008", level: 1, zh: "你觉得自己最大的优点是什么？", en: "What do you think is your biggest strength?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-009", level: 1, zh: "你更喜欢安静约会，还是热闹约会？", en: "Do you prefer quiet dates or lively dates?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-010", level: 1, zh: "你更喜欢白天出去玩，还是晚上出去玩？", en: "Do you prefer going out during the day or at night?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-011", level: 1, zh: "你平时几点睡？几点起床？", en: "What time do you usually go to bed and wake up?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-012", level: 1, zh: "周末你更喜欢宅着，还是出去玩？", en: "On weekends, do you prefer staying in or going out?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-013", level: 1, zh: "你平时会健身或运动吗？", en: "Do you usually work out or play sports?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-014", level: 1, zh: "你吃东西偏清淡还是重口？", en: "Do you prefer lighter food or stronger flavors?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-015", level: 1, zh: "你能吃辣吗？", en: "Can you handle spicy food?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-016", level: 1, zh: "你更喜欢猫还是狗？", en: "Do you prefer cats or dogs?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-017", level: 1, zh: "你平时最常听什么类型的歌？", en: "What kind of music do you listen to most?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-018", level: 1, zh: "你更爱看电影、电视剧，还是短视频？", en: "Do you prefer movies, TV series, or short videos?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-019", level: 1, zh: "旅游你更喜欢海边、城市，还是山里？", en: "When you travel, do you prefer the beach, a city, or the mountains?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-020", level: 1, zh: "出门或旅行时，你更喜欢提前计划，还是到了再说？", en: "When going out or traveling, do you prefer planning ahead or deciding as you go?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-021", level: 1, zh: "你平时更喜欢热闹，还是安静？", en: "Do you generally prefer lively places or quiet ones?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-022", level: 1, zh: "一个人休息的时候，你最喜欢干什么？", en: "What do you like doing most when you're relaxing alone?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-023", level: 1, zh: "最近你最上头的一个爱好是什么？", en: "What's one hobby you're really into lately?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-024", level: 1, zh: "你周末会睡懒觉吗？", en: "Do you sleep in on weekends?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-025", level: 1, zh: "你更喜欢临时约，还是提前约？", en: "Do you prefer spontaneous plans or making plans in advance?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-026", level: 1, zh: "你平时一个人待着的时间多吗？", en: "Do you spend a lot of time on your own?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-027", level: 1, zh: "你喜欢甜食吗？", en: "Do you like sweets?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-028", level: 1, zh: "你更喜欢火锅还是烧烤？", en: "Do you prefer hot pot or barbecue?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-029", level: 1, zh: "你更喜欢啤酒还是鸡尾酒？", en: "Do you prefer beer or cocktails?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-030", level: 1, zh: "你更喜欢热闹有 DJ 的酒吧，还是安静的清吧？", en: "Do you prefer a lively bar with a DJ or a quieter bar?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-031", level: 1, zh: "你喜欢滑雪、冲浪这类运动吗？", en: "Do you like sports such as skiing or surfing?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-032", level: 1, zh: "旅行时你更喜欢拍照，还是专心玩？", en: "When traveling, do you prefer taking photos or just enjoying the moment?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-033", level: 1, zh: "你平时听歌多吗？", en: "Do you listen to music a lot?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-034", level: 1, zh: "你更喜欢电影还是综艺？", en: "Do you prefer movies or variety shows?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-035", level: 1, zh: "你更喜欢喜剧还是悬疑？", en: "Do you prefer comedy or mystery?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-036", level: 1, zh: "你更喜欢电影院，还是私人影院的体验？", en: "Do you prefer a regular cinema or a private screening room?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-037", level: 1, zh: "你更喜欢户外还是室内活动？", en: "Do you prefer outdoor or indoor activities?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-038", level: 1, zh: "你平时会经常拍照吗？", en: "Do you take photos often?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-039", level: 1, zh: "你在熟人面前话多还是话少？", en: "Are you more talkative or quiet around people you know well?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-040", level: 1, zh: "你更喜欢两个人玩，还是一群人玩？", en: "Do you prefer hanging out one-on-one or in a group?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-041", level: 1, zh: "你更喜欢熟人局，还是认识新人的局？", en: "Do you prefer hanging out with people you know or meeting new people?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-042", level: 1, zh: "你喝酒以后会变得更话多吗？", en: "Do you get more talkative after drinking?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-043", level: 1, zh: "你做决定一般很快，还是会纠结很久？", en: "Do you usually decide quickly or overthink for a while?", contentTags: [], timerSeconds: null },
    { id: "TR-L1-044", level: 1, zh: "你属于容易和陌生人熟起来的人吗？", en: "Do you warm up to strangers easily?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-001", level: 2, zh: "你更容易被外貌吸引，还是聊天感觉吸引？", en: "Are you more drawn to looks or to the feeling you get from talking?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-002", level: 2, zh: "你喜欢主动一点的人，还是慢热一点的人？", en: "Do you prefer someone who's more proactive or more slow-burning?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-003", level: 2, zh: "你更喜欢成熟一点的，还是有少年感 / 少女感的？", en: "Do you prefer someone more mature or someone with a youthful vibe?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-004", level: 2, zh: "异性哪个小动作最容易让你加分？", en: "What small gesture from someone you're attracted to earns the most points with you?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-005", level: 2, zh: "异性什么行为最容易让你瞬间下头？", en: "What behavior makes you lose interest in someone instantly?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-006", level: 2, zh: "你更喜欢别人直接表达好感，还是慢慢试探？", en: "Do you prefer someone to show interest directly or test the waters slowly?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-007", level: 2, zh: "你喜欢对方话多一点，还是少一点？", en: "Do you prefer someone who's more talkative or more quiet?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-008", level: 2, zh: "你更喜欢对方有点强势，还是比较温柔？", en: "Do you prefer someone a little more assertive or more gentle?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-009", level: 2, zh: "你更喜欢别人夸你好看，还是夸你有趣？", en: "Would you rather be told you're attractive or that you're fun?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-010", level: 2, zh: "你第一次见异性，最先会看哪里？", en: "When you first meet someone you're attracted to, what do you notice first?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-011", level: 2, zh: "你更吃颜值、身材，还是气质？", en: "What matters more to you: looks, body, or overall vibe?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-012", level: 2, zh: "什么样的异性最容易让你想继续聊下去？", en: "What kind of person makes you want to keep the conversation going?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-013", level: 2, zh: "你觉得男女之间有感觉，一般多久能感觉出来？", en: "How quickly do you think you can tell when there's chemistry between two people?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-014", level: 2, zh: "你更喜欢异性什么类型的穿搭？", en: "What kind of style do you like on someone you're attracted to?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-015", level: 2, zh: "你会因为声音对一个人加分吗？", en: "Can someone's voice make them more attractive to you?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-016", level: 2, zh: "你更容易一见有感觉，还是越聊越有感觉？", en: "Are you more likely to feel a spark right away or after talking for a while?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-017", level: 2, zh: "你会因为一个人的味道对 TA 有好感吗？", en: "Can someone's scent make you more attracted to them?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-018", level: 2, zh: "你会因为一个人的身材对 TA 有好感吗？", en: "Can someone's body make you more attracted to them?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-019", level: 2, zh: "你更喜欢会打扮的，还是自然一点的？", en: "Do you prefer someone who's well-styled or more natural?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-020", level: 2, zh: "你更喜欢对方有主见，还是随和一点？", en: "Do you prefer someone with strong opinions or someone more easygoing?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-021", level: 2, zh: "如果对一个人有好感，你会主动吗？", en: "If you like someone, do you usually make the first move?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-022", level: 2, zh: "你更喜欢自己约人，还是等别人约？", en: "Do you prefer asking someone out or waiting for them to ask you?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-023", level: 2, zh: "第一次单独见面，你更喜欢喝东西、吃饭，还是喝酒？", en: "For a first one-on-one meetup, would you rather get drinks, eat, or have alcohol?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-024", level: 2, zh: "目前为止，你觉得我们两个聊得合拍吗？", en: "So far, do you think the two of us click?", contentTags: [], timerSeconds: null },
    { id: "TR-L2-025", level: 2, zh: "你有好感时会主动给信号吗？", en: "When you like someone, do you usually give them signals?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-001", level: 3, zh: "如果今晚只能夸我一个地方，你会夸哪里？", en: "If you could compliment just one thing about me tonight, what would it be?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-002", level: 3, zh: "你觉得我属于你平时会喜欢的类型吗？", en: "Am I the kind of person you'd usually be attracted to?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-003", level: 3, zh: "你觉得我最容易吸引异性的地方是什么？", en: "What about me do you think is most likely to attract people?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-004", level: 3, zh: "刚认识到现在，你对我的印象变好还是变差了？", en: "Since we met, has your impression of me gotten better or worse?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-005", level: 3, zh: "你喜欢别人主动一点，还是给你一点空间让你慢慢靠近？", en: "Do you prefer someone to move closer first, or give you space to approach at your own pace?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-006", level: 3, zh: "你觉得我属于越看越顺眼的类型吗？", en: "Do you think I'm the kind of person who gets more attractive the longer you look?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-007", level: 3, zh: "你觉得我笑起来加分吗？", en: "Do you think my smile makes me more attractive?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-008", level: 3, zh: "对方坐得很近，你会紧张吗？", en: "Do you get nervous when someone you're attracted to sits very close?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-009", level: 3, zh: "你喜欢对方靠近耳边说话吗？", en: "Do you like it when someone leans in and talks close to your ear?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-010", level: 3, zh: "现在这个距离，你觉得刚好还是有点远？", en: "Does the distance between us right now feel right, or a little too far?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-011", level: 3, zh: "牵手时你喜欢普通牵，还是十指交扣？", en: "When holding hands, do you prefer a regular hold or interlocked fingers?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-012", level: 3, zh: "你更喜欢牵手还是靠肩？", en: "Do you prefer holding hands or leaning on someone's shoulder?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-013", level: 3, zh: "你喜欢身体接触多一点，还是少一点？", en: "Do you prefer more physical contact or less?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-014", level: 3, zh: "别人在你耳边说什么最容易让你脸红？", en: "What could someone whisper in your ear that would make you blush fastest?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-015", level: 3, zh: "如果我们接吻，你觉得谁会先主动？", en: "If we kissed, who do you think would make the first move?", contentTags: [], timerSeconds: null },
    { id: "TR-L3-016", level: 3, zh: "牵手、拥抱、亲脸，只能选一个你选哪个？", en: "If you had to choose one—holding hands, hugging, or a kiss on the cheek—which would you pick?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-001", level: 4, zh: "你喜欢慢一点的吻，还是直接一点的吻？", en: "Do you prefer a slower kiss or a more direct one?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-002", level: 4, zh: "除了嘴唇，你最喜欢被亲哪里？", en: "Other than your lips, where do you most like being kissed?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-003", level: 4, zh: "接吻的时候，你喜欢被搂腰吗？", en: "Do you like being held around the waist while kissing?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-004", level: 4, zh: "接吻的时候，你喜欢对方的手放在哪里？", en: "When kissing, where do you like the other person's hands to be?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-005", level: 4, zh: "你更喜欢正面贴近，还是从背后抱？", en: "Do you prefer being close face-to-face or being hugged from behind?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-006", level: 4, zh: "亲密互动时，你喜欢对方更主动、更主导一点吗？", en: "During intimate moments, do you like the other person to take more of the lead?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-007", level: 4, zh: "你最喜欢哪种挑逗方式？", en: "What kind of teasing turns you on most?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-008", level: 4, zh: "哪种触碰最容易让你兴奋？", en: "What kind of touch turns you on most easily?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-009", level: 4, zh: "你身体哪个位置最敏感？", en: "Which part of your body is the most sensitive?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-010", level: 4, zh: "你喜欢对方说暧昧的话吗？", en: "Do you like it when someone says suggestive things to you?", contentTags: [], timerSeconds: null },
    { id: "TR-L4-011", level: 4, zh: "你现在最想摸我哪里？", en: "Where would you most want to touch me right now?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-001", level: 5, zh: "你觉得前戏重要吗？", en: "Do you think foreplay is important?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-002", level: 5, zh: "你更喜欢长一点的前戏，还是快速进入状态？", en: "Do you prefer longer foreplay or getting into it quickly?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-003", level: 5, zh: "你喜欢被打屁股吗？", en: "Do you like being spanked?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-004", level: 5, zh: "你更喜欢开灯还是关灯？", en: "Do you prefer the lights on or off?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-005", level: 5, zh: "你更喜欢安静，还是放着音乐？", en: "Do you prefer silence or having music on?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-006", level: 5, zh: "你会直接说自己想要怎样被满足吗？", en: "Do you directly say how you want to be pleased?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-007", level: 5, zh: "你最喜欢别人夸你身体哪个部位？", en: "Which part of your body do you most like being complimented on?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-008", level: 5, zh: "你有没有特别容易让你兴奋的特殊偏好？", en: "Do you have any particular preference that turns you on especially quickly?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-009", level: 5, zh: "你对蒙眼有兴趣吗？", en: "Are you interested in being blindfolded?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-010", level: 5, zh: "你对轻度束缚有兴趣吗？", en: "Are you interested in light bondage?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-011", level: 5, zh: "你对角色扮演有兴趣吗？", en: "Are you interested in role-play?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-012", level: 5, zh: "你对性玩具有兴趣吗？", en: "Are you interested in sex toys?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-013", level: 5, zh: "你更喜欢在床上，还是别的地方？", en: "Do you prefer sex in bed or somewhere else?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-014", level: 5, zh: "你更喜欢早上还是晚上？", en: "Do you prefer sex in the morning or at night?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-015", level: 5, zh: "你最喜欢哪种性爱节奏？", en: "What kind of sexual pace do you like most?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-016", level: 5, zh: "你有没有特别想尝试的姿势？", en: "Is there a position you especially want to try?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-017", level: 5, zh: "你最想尝试的一种性幻想是什么？", en: "What's one sexual fantasy you'd most like to try?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-018", level: 5, zh: "你最想试、但一直没试过的是什么？", en: "What's something you've really wanted to try but haven't yet?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-019", level: 5, zh: "你接受亲密时候说露骨一点的话吗？", en: "Are you into more explicit talk during intimate moments?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-020", level: 5, zh: "你觉得亲密的时候，时间长一点好，还是短一点但刺激更重要？", en: "During intimate moments, do you prefer longer sessions or shorter but more intense ones?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-021", level: 5, zh: "你最喜欢哪一种姿势？", en: "What's your favorite sex position?", contentTags: [], timerSeconds: null },
    { id: "TR-L5-022", level: 5, zh: "如果今晚完全不用害羞，你最想和我尝试什么？", en: "If you didn't have to feel shy at all tonight, what would you most want to try with me?", contentTags: [], timerSeconds: null },
];
