import type { Challenge } from "@/lib/punishment/schema";

// 「一男一女」正式题库 V1.0（Human 审核入库，108 题）。暂不设盾牌标签：contentTags 全为空数组。
export const challenges: Challenge[] = [
    { id: "DA-DUO-L1-001", level: 1, zh: "站起来，大声说 3 遍。男生说：“全场我最帅！”；女生说：“全场我最美！”", en: "Stand up and say this loudly three times. Men: “I’m the hottest guy here!” Women: “I’m the hottest woman here!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-002", level: 1, zh: "站起来，看着对方大声说：“这轮输家就是我！”", en: "Stand up, look at your opponent, and shout, “I’m the loser this round!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-003", level: 1, zh: "站起来，大声说：“我输了，但我的颜值没输！”", en: "Stand up and shout, “I lost, but my looks didn’t!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-004", level: 1, zh: "站起来，大声说：“我这么优秀还会输，合理吗？”", en: "Stand up and shout, “I’m this great and I still lost—how does that make sense?”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-005", level: 1, zh: "站起来，大声说：“全场注意，我今天负责丢脸！”", en: "Stand up and shout, “Attention, everyone! I’m in charge of embarrassing myself tonight!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-006", level: 1, zh: "站起来，大声说：“今晚谁都别劝我低调！”", en: "Stand up and shout, “Nobody tell me to tone it down tonight!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-007", level: 1, zh: "站起来，大声说：“我宣布，今晚最需要被照顾的人是我！”", en: "Stand up and shout, “I hereby declare: I’m the one who needs the most looking after tonight!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-008", level: 1, zh: "站起来，大声说：“我不是菜，我是在给大家面子！”", en: "Stand up and shout, “I’m not bad at this—I’m just making everyone else look good!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-009", level: 1, zh: "站起来，大声说：“输的是我，气势不能输！”", en: "Stand up and shout, “I may have lost, but I’m not losing the swagger!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-010", level: 1, zh: "站起来，大声说：“下一把再输，我还敢站起来！”", en: "Stand up and shout, “If I lose the next round too, I’ll still stand up and own it!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-011", level: 1, zh: "站起来，对对方举杯，大声说：“以后罩着我！”然后自己喝一小口。", en: "Stand up, raise your glass to your opponent, and shout, “You’ve got my back from now on!” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-012", level: 1, zh: "面对对方认真鞠躬 3 次，每次都说：“服了。”", en: "Face your opponent, bow three times, and say “You got me” each time.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-013", level: 1, zh: "面对对方双手抱拳，大声说：“好汉饶命！”", en: "Face your opponent, clasp your hands, and shout, “Have mercy!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-014", level: 1, zh: "面对对方举起双手做投降状 10 秒，再说：“这把你赢。”", en: "Face your opponent, hold both hands up in surrender for 10 seconds, then say, “You win this one.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L1-015", level: 1, zh: "指着对方，再指着自己，大声说：“你是大哥/姐姐，我是小弟/小妹。”", en: "Point at your opponent, then at yourself, and shout, “You’re the boss; I’m your sidekick.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-016", level: 1, zh: "面对对方敬礼 5 秒，然后说：“收到，服从安排。”", en: "Salute your opponent for 5 seconds, then say, “Roger that. Orders received.”", contentTags: [], timerSeconds: 5 },
    { id: "DA-DUO-L1-017", level: 1, zh: "对对方竖起两个大拇指，大声说：“这把你确实厉害。”", en: "Give your opponent two thumbs up and shout, “You really got me this round.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-018", level: 1, zh: "站起来向对方鞠一躬，说：“这轮我认栽。”", en: "Stand up, bow to your opponent, and say, “I admit defeat this round.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-019", level: 1, zh: "一只手放胸口，面对对方认真说：“我向强者低头。”", en: "Put one hand on your chest, face your opponent, and say seriously, “I bow to the better player.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-020", level: 1, zh: "面对对方双手合十 10 秒，说：“下一把请轻一点。”", en: "Face your opponent with your palms together for 10 seconds and say, “Go easy on me next round.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L1-021", level: 1, zh: "站起来举杯，大声说：“这口算我罚的！”然后自己喝一小口。", en: "Stand up, raise your glass, and shout, “This sip is my penalty!” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-022", level: 1, zh: "把杯子举到胸前，大声说：“敬我今天的失败！”然后自己喝一小口。", en: "Hold your glass at chest level and shout, “Here’s to today’s defeat!” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-023", level: 1, zh: "一只手放胸口，举杯说：“敬今晚最会输的人。”然后自己喝一小口。", en: "Put one hand on your chest, raise your glass, and say, “To tonight’s biggest loser.” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-024", level: 1, zh: "双手捧着杯子，大声说：“最佳输家奖，我收下了！”然后喝一小口。", en: "Hold your glass with both hands and shout, “I’ll take the Best Loser award!” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-025", level: 1, zh: "先对自己的杯子鞠一躬，说：“辛苦你陪我丢脸。”然后喝一小口。", en: "Bow to your own glass and say, “Thanks for sticking with me through this embarrassment.” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-026", level: 1, zh: "指着自己的杯子说：“你今天害我不浅。”然后自己喝一小口。", en: "Point at your glass and say, “You really got me into trouble tonight.” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-027", level: 1, zh: "把杯子举到眼前，说：“这口买回我的面子。”然后自己喝一小口。", en: "Hold your glass at eye level and say, “This sip is buying back my dignity.” Then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-028", level: 1, zh: "轻敲桌面 3 下，大声说：“我认罚！”然后自己喝一小口。", en: "Tap the table three times, shout, “I accept the penalty!” and take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-029", level: 1, zh: "抱着自己的杯子 5 秒，说：“今天只有你不会笑我。”然后喝一小口。", en: "Hug your glass for 5 seconds and say, “You’re the only one who won’t laugh at me tonight.” Then take a small sip.", contentTags: [], timerSeconds: 5 },
    { id: "DA-DUO-L1-030", level: 1, zh: "双手举过头顶比一个大爱心，保持 10 秒。", en: "Raise both hands over your head and make a big heart for 10 seconds.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L1-031", level: 1, zh: "双手举高做投降状，保持 10 秒，说：“我没有意见。”", en: "Hold both hands up in surrender for 10 seconds and say, “No objections.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L1-032", level: 1, zh: "双臂在胸前交叉成一个大“X”，保持 10 秒，说：“拒绝继续输。”", en: "Cross your arms into a big X over your chest for 10 seconds and say, “I refuse to keep losing.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L1-033", level: 1, zh: "双手合十放在胸前，连续鞠躬 3 次，说：“求放过。”", en: "Put your palms together at your chest, bow three times, and say, “Please spare me.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-034", level: 1, zh: "一只手捂住脸，另一只手向对方挥手，说：“没脸见人了。”", en: "Cover your face with one hand, wave to your opponent with the other, and say, “I’m too embarrassed to show my face.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-035", level: 1, zh: "双臂向两侧完全张开，保持 10 秒，说：“接受大家审判。”", en: "Stretch both arms fully out to your sides for 10 seconds and say, “Go ahead, judge me.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L1-036", level: 1, zh: "站起来，向对方认真鞠躬 3 次。", en: "Stand up and bow seriously to your opponent three times.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-037", level: 1, zh: "站起来，给自己鼓掌 10 下，再向对方鞠一躬。", en: "Stand up, applaud yourself ten times, then bow to your opponent.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-038", level: 1, zh: "站起来，一只手放胸口，大声说：“谢谢大家给我这个丢脸的机会。”", en: "Stand up, put one hand on your chest, and shout, “Thank you all for giving me this chance to embarrass myself.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-039", level: 1, zh: "站起来，向对方敬礼 5 秒，说：“报告，我又输了。”", en: "Stand up, salute your opponent for 5 seconds, and say, “Reporting in: I lost again.”", contentTags: [], timerSeconds: 5 },
    { id: "DA-DUO-L1-040", level: 1, zh: "站起来，先向左边点头，再向右边点头，说：“谢谢各位见证。”", en: "Stand up, nod once to the left and once to the right, and say, “Thanks, everyone, for witnessing this.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L1-041", level: 1, zh: "站起来，双手抱拳，朝对方说：“好汉，手下留情。”", en: "Stand up, clasp your hands toward your opponent, and say, “Have mercy on me.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-001", level: 2, zh: "对方端着你的杯子喂你喝一小口。", en: "Your opponent holds your glass and feeds you a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-002", level: 2, zh: "你站起来举杯，大声说：“以后罩着我！”对方和你碰杯，只有你喝一小口。", en: "Stand up with your glass and shout, “You’ve got my back from now on!” Clink glasses with your opponent; only you take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-003", level: 2, zh: "和对方击掌 3 次；你大声说：“这轮算你狠。”", en: "High-five your opponent three times, then shout, “You got me this round.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-004", level: 2, zh: "挽住对方的大臂，自己喝一小口。", en: "Hold onto your opponent’s upper arm and take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-005", level: 2, zh: "把一只手搭在对方肩膀上，自己喝一小口。", en: "Put one hand on your opponent’s shoulder and take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-006", level: 2, zh: "和对方击掌一次，然后你自己喝一小口。", en: "High-five your opponent once, then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-007", level: 2, zh: "和对方握手 3 秒，再自己喝一小口。", en: "Shake hands with your opponent for 3 seconds, then take a small sip.", contentTags: [], timerSeconds: 3 },
    { id: "DA-DUO-L2-008", level: 2, zh: "和对方击掌 3 次；你最后说：“下一轮再来。”", en: "High-five your opponent three times, then say, “Next round.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-009", level: 2, zh: "轻拍对方肩膀 3 下；你说：“下一轮等着。”", en: "Lightly pat your opponent’s shoulder three times and say, “Just wait till next round.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-010", level: 2, zh: "你和对方一起举杯；你站起来大声说：“今晚你别装！”然后只有你喝一小口。", en: "Raise your glasses together. Stand up and shout, “No pretending tonight!” Then only you take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-011", level: 2, zh: "你和对方一起举杯；你站起来大声说：“下一把轻点！”然后只有你喝一小口。", en: "Raise your glasses together. Stand up and shout, “Go easy on me next round!” Then only you take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-012", level: 2, zh: "你和对方一起举杯；你大声说：“今天我先认罚！”然后只有你喝一小口。", en: "Raise your glasses together. Shout, “I’ll take the penalty this round!” Then only you take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-013", level: 2, zh: "你和对方一起举杯；你大声说：“这轮你赢了！”然后只有你喝一小口。", en: "Raise your glasses together. Shout, “You win this round!” Then only you take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-014", level: 2, zh: "你和对方一起举杯；你大声说：“下一轮继续收拾我！”然后只有你喝一小口。", en: "Raise your glasses together. Shout, “Come at me again next round!” Then only you take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-015", level: 2, zh: "你和对方一起举杯；你大声说：“我先给你助个兴！”然后只有你喝一小口。", en: "Raise your glasses together. Shout, “I’ll get the party going for you!” Then only you take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-016", level: 2, zh: "对方向你竖大拇指，你站起来说：“这点面子我收下了！”", en: "Your opponent gives you a thumbs-up. Stand up and say, “I’ll take the support!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-017", level: 2, zh: "和对方碰拳一次，最后大声说：“下一轮见。”", en: "Fist-bump your opponent once, then shout, “See you next round!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-018", level: 2, zh: "和对方轻碰一次杯，最后自己喝一小口。", en: "Clink glasses lightly with your opponent once, then take a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-019", level: 2, zh: "对方指向你，你站起来大声说：“没错，输家就是我！”", en: "Your opponent points at you. Stand up and shout, “Yep, I’m the loser!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-020", level: 2, zh: "你和对方一起举杯，你站起来说：“今晚我最需要被照顾！”", en: "Raise your glasses together. Stand up and say, “I’m the one who needs the most looking after tonight!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-021", level: 2, zh: "对方拍桌一下，你站起来说：“我接受现实！”", en: "Your opponent taps the table once. Stand up and say, “I accept reality!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-022", level: 2, zh: "对方向你竖大拇指，你站起来说：“这点安慰我收下了！”", en: "Your opponent gives you a thumbs-up. Stand up and say, “I’ll take the consolation!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L2-023", level: 2, zh: "你和对方碰杯一次，你站起来说：“输归输，继续玩！”", en: "Clink glasses with your opponent once. Stand up and say, “I lost, but we keep playing!”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L3-001", level: 3, zh: "你和对方肩膀贴肩膀坐着，勾住小拇指，转头对视 10 秒，同时说：“你今晚还挺顺眼。”", en: "Sit shoulder-to-shoulder, hook pinkies, turn to face each other, and hold eye contact for 10 seconds while both saying, “You look pretty good tonight.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L3-002", level: 3, zh: "用双手给对方一侧上臂按摩 30 秒。", en: "Massage one of their upper arms with both hands for 30 seconds.", contentTags: [], timerSeconds: 30 },
    { id: "DA-DUO-L3-003", level: 3, zh: "面对面帮对方整理衣领 10 秒。", en: "Face them and straighten their collar for 10 seconds.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L3-004", level: 3, zh: "你和对方面对面对视 10 秒；你看着对方说：“今晚你最好看。”", en: "Hold eye contact for 10 seconds, then look at them and say, “You’re the best-looking person here tonight.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L3-005", level: 3, zh: "男生屈臂绷紧二头肌，女生用一只手完整握住 10 秒，再直接报一个 1～10 分。", en: "The man flexes his biceps; the woman grips one biceps with one hand for 10 seconds, then gives it a score from 1 to 10.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L3-006", level: 3, zh: "你和对方勾住小拇指，对视 10 秒，同时说：“你今晚还挺顺眼。”", en: "Hook pinkies, hold eye contact for 10 seconds, and say together, “You look pretty good tonight.”", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L3-007", level: 3, zh: "你和对方对视 10 秒；你看着对方慢慢飞一个吻。", en: "Hold eye contact for 10 seconds, then slowly blow them a kiss.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L3-008", level: 3, zh: "你和对方十指相扣放在桌面上，面对面对视 15 秒。", en: "Interlace fingers on the table and hold face-to-face eye contact for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L3-009", level: 3, zh: "你和对方面对面靠近到鼻尖相距约 10 厘米，对视 15 秒。", en: "Move face-to-face until your noses are about 10 cm apart, then hold eye contact for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L3-010", level: 3, zh: "你和对方额头贴额头，十指相扣，保持 15 秒。", en: "Touch foreheads, interlace fingers, and hold for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L3-011", level: 3, zh: "贴近对方耳边说：“今晚我只注意到你。”", en: "Lean close to their ear and say, “Tonight, you’re the only one I’ve noticed.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L3-012", level: 3, zh: "站到对方身后，双手给对方肩颈按摩 30 秒。", en: "Stand behind them and massage their shoulders and neck with both hands for 30 seconds.", contentTags: [], timerSeconds: 30 },
    { id: "DA-DUO-L3-013", level: 3, zh: "握住对方一只手，用拇指按摩对方掌心 30 秒；两人面对面对视。", en: "Hold one of their hands and massage their palm with your thumb for 30 seconds while maintaining eye contact.", contentTags: [], timerSeconds: 30 },
    { id: "DA-DUO-L3-014", level: 3, zh: "你和对方十指相扣放在桌面上，对视着一起唱：“十年之前，我不认识你；你不属于我；我们还是一样，陪在一个陌生人左右。”", en: "Interlace fingers on the table, hold eye contact, and sing together: “Ten years ago, I didn’t know you / You weren’t mine / We were still the same, staying beside a stranger.”", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L3-015", level: 3, zh: "男生输：男生掀起上衣露出腹部并绷紧腹肌，女生把一只手掌完整贴在腹肌上 15 秒；女生输：女生把一只手掌完整贴在男生胸肌外侧 15 秒，男生同时绷紧胸肌。两人全程对视。", en: "If the man loses, he lifts his shirt and flexes his abs while the woman keeps one palm flat on them for 15 seconds. If the woman loses, she keeps one palm flat on the outer part of the man’s chest for 15 seconds while he flexes. Maintain eye contact throughout.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L3-016", level: 3, zh: "你和对方面对面对视 15 秒；你看着对方大声说：“我喜欢你。”", en: "Hold face-to-face eye contact for 15 seconds, then look at them and say loudly, “I like you.”", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L3-017", level: 3, zh: "你和对方并排坐，膝盖贴膝盖 15 秒，同时转头看着对方。", en: "Sit side by side with your knees touching for 15 seconds and turn to look at each other.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L3-018", level: 3, zh: "你和对方面对面握手 10 秒，同时看着对方。", en: "Shake hands face-to-face for 10 seconds while maintaining eye contact.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L4-001", level: 4, zh: "面对面双臂环住对方腰部，抱 15 秒。", en: "Face them, wrap both arms around their waist, and hug for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L4-002", level: 4, zh: "单臂搂住对方腰侧抱 15 秒，并贴近对方耳边说：“今晚别离我太远。”", en: "Put one arm around their waist from the side for 15 seconds and whisper, “Don’t go too far from me tonight.”", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L4-003", level: 4, zh: "你和对方手臂交叉挽住，各喝一小口交杯酒；喝的时候一直看着对方。", en: "Link arms and each take a small sip while maintaining eye contact.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L4-004", level: 4, zh: "一只手搂住对方腰，另一只手互相喂对方喝一小口酒。", en: "Put one arm around their waist and feed each other a small sip.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L4-005", level: 4, zh: "让对方把一条小腿搭在你大腿上；你双手给对方小腿按摩 30 秒。", en: "Have them rest one lower leg across your thigh, then massage their calf with both hands for 30 seconds.", contentTags: [], timerSeconds: 30 },
    { id: "DA-DUO-L4-006", level: 4, zh: "你坐到对方腿上 15 秒，两人面对面对视。", en: "Sit on their lap for 15 seconds and maintain face-to-face eye contact.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L4-007", level: 4, zh: "让对方枕在你大腿上；两人十指相扣，对视 15 秒。", en: "Have them rest their head on your lap, interlace fingers, and hold eye contact for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L4-008", level: 4, zh: "双手轻扶对方肩膀，亲一下对方脸颊。", en: "Lightly hold both of their shoulders and kiss them once on the cheek.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L4-009", level: 4, zh: "一只手轻扶对方后颈，亲一下对方额头。", en: "Rest one hand behind their neck and kiss them once on the forehead.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L4-010", level: 4, zh: "双手捧住对方脸颊，亲一下对方鼻尖。", en: "Cup their cheeks with both hands and kiss the tip of their nose once.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L4-011", level: 4, zh: "握住对方一只手，先亲一下手背，再亲一下脸颊。", en: "Hold one of their hands, kiss the back of it once, then kiss their cheek once.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L4-012", level: 4, zh: "你站到对方面前，一只手撑在对方身侧的墙或椅背上，两人对视 15 秒。", en: "Stand close, brace one hand on the wall or chair beside them, and hold eye contact for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L4-013", level: 4, zh: "你单膝跪下并握住对方一只手；对方亲一下你的额头。", en: "Kneel on one knee and hold one of their hands; they kiss your forehead once.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L4-014", level: 4, zh: "从背后双臂环住对方腰，抱 15 秒。", en: "Wrap both arms around their waist from behind and hug for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L4-015", level: 4, zh: "双手扶住对方腰，两人鼻尖相距约 5 厘米，对视 15 秒。", en: "Put both hands on their waist, keep your noses about 5 cm apart, and hold eye contact for 15 seconds.", contentTags: [], timerSeconds: 15 },
    { id: "DA-DUO-L5-001", level: 5, zh: "你和对方面对面接吻 10 秒。", en: "Kiss face-to-face for 10 seconds.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L5-002", level: 5, zh: "你和对方十指相扣，对视 10 秒，再接吻 10 秒。", en: "Interlace fingers, hold eye contact for 10 seconds, then kiss for 10 seconds.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L5-003", level: 5, zh: "你和对方额头贴额头、十指相扣 10 秒，再接吻 10 秒。", en: "Touch foreheads and interlace fingers for 10 seconds, then kiss for 10 seconds.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L5-004", level: 5, zh: "一只手搂住对方腰，亲一下对方脖子侧面。", en: "Put one arm around their waist and kiss the side of their neck once.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L5-005", level: 5, zh: "一只手扶住对方下巴，亲一下对方嘴角。", en: "Hold their chin with one hand and kiss the corner of their mouth once.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L5-006", level: 5, zh: "从正面双臂抱住对方腰，亲一下对方耳朵。", en: "Hug their waist from the front and kiss their ear once.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L5-007", level: 5, zh: "你坐到对方腿上 20 秒；两人十指相扣，全程对视。", en: "Sit on their lap for 20 seconds with your fingers interlaced and maintain eye contact throughout.", contentTags: [], timerSeconds: 20 },
    { id: "DA-DUO-L5-008", level: 5, zh: "让对方枕在你大腿上；两人十指相扣，对视 20 秒。", en: "Have them rest their head on your lap, interlace fingers, and hold eye contact for 20 seconds.", contentTags: [], timerSeconds: 20 },
    { id: "DA-DUO-L5-009", level: 5, zh: "依次亲对方手背、脸颊、额头；每个部位只亲 1 次。", en: "Kiss the back of their hand, their cheek, and their forehead once each.", contentTags: [], timerSeconds: null },
    { id: "DA-DUO-L5-010", level: 5, zh: "一只手搂住对方腰，贴近对方耳边轻吹 10 秒。", en: "Put one arm around their waist, lean close to their ear, and gently blow for 10 seconds.", contentTags: [], timerSeconds: 10 },
    { id: "DA-DUO-L5-011", level: 5, zh: "你和对方鼻尖贴住、十指相扣，闭眼保持 15 秒。", en: "Touch noses, interlace fingers, close your eyes, and hold for 15 seconds.", contentTags: [], timerSeconds: 15 },
];
